-- Rubik OS - Core schema compatibility and RLS.
-- Compatibility phase for quotes.status plus RLS on 008 operational tables.
-- This migration does not rewrite business rows.

alter table if exists public.quotes
  drop constraint if exists quotes_status_check;

do $$
begin
  if to_regclass('public.quotes') is not null
    and exists (
      select 1
      from pg_constraint
      where conrelid = 'public.quotes'::regclass
        and conname = 'quotes_operational_status_check'
    )
  then
    alter table public.quotes
      rename constraint quotes_operational_status_check to quotes_status_check;
  end if;
end;
$$;

alter table if exists public.quotes
  drop constraint if exists quotes_status_check;

do $$
begin
  if to_regclass('public.quotes') is not null
    and not exists (
      select 1
      from pg_constraint
      where conrelid = 'public.quotes'::regclass
        and conname = 'quotes_status_check'
    )
  then
    alter table public.quotes
      add constraint quotes_status_check check (
        status in (
          'borrador',
          'tentativo',
          'esperando_revision_diego',
          'aprobado_por_diego',
          'enviado_cliente',
          'aceptado_cliente',
          'rechazado_cliente',
          'vencido',
          'requiere_actualizacion',
          'confirmado',
          'enviada_cliente',
          'vencida',
          'rechazada'
        )
      ) not valid;
  end if;
end;
$$;

alter table if exists public.clients enable row level security;
alter table if exists public.contact_channels enable row level security;
alter table if exists public.client_contacts enable row level security;
alter table if exists public.work_orders enable row level security;
alter table if exists public.work_order_status_history enable row level security;
alter table if exists public.messages enable row level security;
alter table if exists public.attachments enable row level security;
alter table if exists public.measurements enable row level security;
alter table if exists public.designs enable row level security;
alter table if exists public.design_modules enable row level security;
alter table if exists public.design_parts enable row level security;
alter table if exists public.approvals enable row level security;
alter table if exists public.blockers enable row level security;
alter table if exists public.dependencies enable row level security;
alter table if exists public.planning_alerts enable row level security;
alter table if exists public.project_reactivations enable row level security;
alter table if exists public.payments enable row level security;
alter table if exists public.appointments enable row level security;
alter table if exists public.suppliers enable row level security;
alter table if exists public.supplier_requests enable row level security;
alter table if exists public.inventory_items enable row level security;
alter table if exists public.post_sale_cases enable row level security;

comment on constraint quotes_status_check on public.quotes is
  'Temporary compatibility check that permits legacy and new Rubik OS quote statuses. A future normalization migration can narrow this list.';

comment on table public.clients is
  'Base client records for Rubik OS. RLS enabled; policies are intentionally deferred.';
comment on table public.contact_channels is
  'Inbound and outbound contact channel catalog. RLS enabled; policies are intentionally deferred.';
comment on table public.client_contacts is
  'Client contact values by channel. RLS enabled; policies are intentionally deferred.';
comment on table public.work_orders is
  'Central operational entity. RLS enabled; policies are intentionally deferred.';
comment on table public.work_order_status_history is
  'Audit trail of work order status transitions. RLS enabled; policies are intentionally deferred.';
comment on table public.messages is
  'Messages linked to work orders and clients. RLS enabled; policies are intentionally deferred.';
comment on table public.attachments is
  'Files linked to orders, messages or clients. RLS enabled; policies are intentionally deferred.';
comment on table public.measurements is
  'Approximate or confirmed measurements. RLS enabled; policies are intentionally deferred.';
comment on table public.designs is
  'Rubik Design Engine proposals and technical designs. RLS enabled; policies are intentionally deferred.';
comment on table public.design_modules is
  'Modules placed inside a design. RLS enabled; policies are intentionally deferred.';
comment on table public.design_parts is
  'Parts generated by a design or module. RLS enabled; policies are intentionally deferred.';
comment on table public.approvals is
  'Critical approvals. RLS enabled; policies are intentionally deferred.';
comment on table public.blockers is
  'Operational blockers. RLS enabled; policies are intentionally deferred.';
comment on table public.dependencies is
  'Internal and external dependencies. RLS enabled; policies are intentionally deferred.';
comment on table public.planning_alerts is
  'Planning AI alerts. RLS enabled; policies are intentionally deferred.';
comment on table public.project_reactivations is
  'Paused project reactivation reviews. RLS enabled; policies are intentionally deferred.';
comment on table public.payments is
  'Deposits, partial payments, final payments and refunds. RLS enabled; policies are intentionally deferred.';
comment on table public.appointments is
  'Tentative and confirmed operational appointments. RLS enabled; policies are intentionally deferred.';
comment on table public.suppliers is
  'Suppliers and external providers. RLS enabled; policies are intentionally deferred.';
comment on table public.supplier_requests is
  'Supplier requests and responses. RLS enabled; policies are intentionally deferred.';
comment on table public.inventory_items is
  'Basic inventory records. RLS enabled; policies are intentionally deferred.';
comment on table public.post_sale_cases is
  'Post-sale cases. RLS enabled; policies are intentionally deferred.';
